<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Word to PDF</AssemblyName>
    <RootNamespace>Word_to_PDF</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <TargetFrameworkVersion>
    </TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\Settings.settings" />
    <PackageReference Include="Syncfusion.Compression.Base" Version="31.2.2." />
    <PackageReference Include="Syncfusion.DocIO.Wpf" Version="31.2.2." />
    <PackageReference Include="Syncfusion.DocToPDFConverter.Wpf" Version="31.2.2." />
    <PackageReference Include="Syncfusion.OfficeChart.Base" Version="31.2.2." />
    <PackageReference Include="Syncfusion.OfficeChartToImageConverter.WPF" Version="31.2.2." />
    <PackageReference Include="Syncfusion.Pdf.Wpf" Version="31.2.2." />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="31.2.2." />
    <PackageReference Include="Syncfusion.Shared.Base" Version="31.2.2." />
    <PackageReference Include="Syncfusion.SfChart.WPF" Version="31.2.2." />
    <PackageReference Include="Syncfusion.Licensing" Version="31.2.2." />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
</Project>