<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>Syncfusion.XlsIODemos.Winforms.ChartWorksheet</AssemblyName>
    <RootNamespace>ReportFromTemplate</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
    <TargetFrameworkVersion>
    </TargetFrameworkVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Properties\**" />
    <EmbeddedResource Remove="Properties\**" />
    <None Remove="Properties\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Syncfusion.Compression.Base" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Licensing" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Shared.Base" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Shared.Windows" Version="34.1.29" />
    <PackageReference Include="Syncfusion.SpellChecker.Base" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Tools.Base" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Tools.Windows" Version="34.1.29" />
    <PackageReference Include="Syncfusion.XlsIO.WinForms" Version="34.1.29" />
    <PackageReference Include="Syncfusion.Markdown" Version="34.1.29" />
  </ItemGroup>
  <ItemGroup>
    <None Include="packages.config" />
  </ItemGroup>
</Project>