#region Copyright Syncfusion Inc. 2001 - 2005
//
//  Copyright Syncfusion Inc. 2001 - 2005. All rights reserved.
//
//  Use of this code is subject to the terms of our license.
//  A copy of the current license can be obtained at any time by e-mailing
//  licensing@syncfusion.com. Re-distribution in any form is strictly
//  prohibited. Any infringement will be prosecuted under applicable laws. 
//
#endregion

using System;
using System.Drawing;
using System.Drawing.Imaging;
using System.Collections;
using System.ComponentModel;
using System.Windows.Forms;
using System.Data;
using Syncfusion.Pdf;
using Syncfusion.Windows.Forms;
using Syncfusion.Pdf.Interactive;
using Syncfusion.Pdf.Graphics;
using System.Drawing.Text;
using Syncfusion.Licensing;

namespace EssentialPDFSamples
{
    /// <summary>
    /// Summary description for Form1.
    /// </summary>
    public class Form1 : MetroForm
    {
        # region Private Members

        private Label label1;
        private PictureBox pictureBox1;
        private Button button1;
        private PdfDocument document;
        private Font f;
        private PdfFont pdfFont;
        private PdfBrush solidBrush;
        private PdfImage img;
        private RectangleF bounds;
        private SizeF pageSize;
        private PdfPage page;
        private PdfCheckBoxField chb;
        private PdfComboBoxField comboBox;
        private float x;
        # endregion

        # region Constructor and Load
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.Container components = null;

        public Form1()
        {
            //
            // Required for Windows Form Designer support
            //
            InitializeComponent();
            this.MinimizeBox = true;
            this.FormBorderStyle = FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.StartPosition = FormStartPosition.CenterScreen;
            x = 25;
            //
            // TODO: Add any constructor code after InitializeComponent call
            //
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (components != null)
                {
                    components.Dispose();
                }
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.label1 = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.Font = new System.Drawing.Font("Verdana", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(64)))));
            this.label1.Location = new System.Drawing.Point(0, 100);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(374, 87);
            this.label1.TabIndex = 71;
            this.label1.Text = "Click the button to view an PDF document generated by Essential PDF.  Please note" +
                " that Adobe Reader or its equivalent is required to view the resultant document." +
                "";
            // 
            // pictureBox1
            // 
            this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top;
            this.pictureBox1.Image = System.Drawing.Image.FromFile(GetFullTemplatePath("pdf_header.png", true));
            this.pictureBox1.Location = new System.Drawing.Point(0, 0);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(374, 92);
            this.pictureBox1.SizeMode = PictureBoxSizeMode.StretchImage;
            this.pictureBox1.TabIndex = 72;
            this.pictureBox1.TabStop = false;
            // 
            // button1
            // 
            this.button1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.button1.BackColor = System.Drawing.Color.Transparent;
            this.button1.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(192)))), ((int)(((byte)(128)))));
            this.button1.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(224)))), ((int)(((byte)(192)))));
            this.button1.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(255)))), ((int)(((byte)(192)))));
            this.button1.ImageAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.button1.Location = new System.Drawing.Point(289, 148);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(75, 24);
            this.button1.TabIndex = 74;
            this.button1.Text = "PDF";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new System.EventHandler(this.button1_Click);
            // 
            // Form1
            // 
            //this.AutoScaleBaseSize = new System.Drawing.Size(5, 13);
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(380, 194);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.pictureBox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.Icon = System.Drawing.Icon.ExtractAssociatedIcon(GetFullTemplatePath("syncfusion.ico", true));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Form1";
            this.Text = "Job Application";
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.ResumeLayout(false);

        }
        #endregion

        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
			SyncfusionLicenseProvider.RegisterLicense(DemoCommon.FindLicenseKey());
            Application.EnableVisualStyles();
            Application.Run(new Form1());
        }
        # endregion

        # region Events
        private void button1_Click(object sender, System.EventArgs e)
        {
            // Create a new instance of PdfDocument class.
            document = new PdfDocument();

            // Set viewer preferences for the reader 
            document.ViewerPreferences.HideMenubar = true;
            document.ViewerPreferences.HideWindowUI = true;
            document.ViewerPreferences.HideToolbar = true;
            document.ViewerPreferences.FitWindow = true;

            // Build Job Application PDF (2 pages) similar to JobApplication.cshtml.cs
            CreateFirstPage();
            CreateSecondPage();

            // Save the document to disk and close it.
            document.Save("Sample.pdf");
            document.Close(true);

            //Message box confirmation to view the created PDF document.
            if (MessageBox.Show("Do you want to view the PDF file?", "PDF File Created",
                MessageBoxButtons.YesNo, MessageBoxIcon.Information)
                == DialogResult.Yes)
            {
                //Launching the PDF file using the default Application.[Acrobat Reader]
#if NETCORE
                System.Diagnostics.Process process = new System.Diagnostics.Process();
                process.StartInfo = new System.Diagnostics.ProcessStartInfo("Sample.pdf")
                {
                    UseShellExecute = true
                };
                process.Start();
#else
                System.Diagnostics.Process.Start("Sample.pdf");
#endif
                this.Close();
            }
            else
            {
                // Exit
                this.Close();
            }
        }

        # endregion

        # region Helpher Methods

        /// <summary>
        /// Creates second page in the document.
        /// </summary>
        private void CreateSecondPage()
        {
            // Create second page per the sample (Employment Type, Declaration, Signature, T&Cs, Submit)
            PdfPage page2 = document.Pages.Add();
            PdfGraphics g2 = page2.Graphics;

            // Fonts
            PdfFont titleFont = new PdfStandardFont(PdfFontFamily.Helvetica, 17, PdfFontStyle.Regular);
            PdfFont subTitleFont = new PdfStandardFont(PdfFontFamily.Helvetica, 9, PdfFontStyle.Regular);
            PdfFont normalFont = new PdfStandardFont(PdfFontFamily.Helvetica, 10, PdfFontStyle.Regular);
            PdfFont boldFont = new PdfStandardFont(PdfFontFamily.Helvetica, 10, PdfFontStyle.Bold);

            // Brushes and pens
            PdfSolidBrush tealBrush = new PdfSolidBrush(new PdfColor(0, 128, 128));
            PdfSolidBrush blackBrush = new PdfSolidBrush(new PdfColor(0, 0, 0));
            PdfSolidBrush whiteBrush = new PdfSolidBrush(new PdfColor(255, 255, 255));
            PdfPen grayPen = new PdfPen(new PdfColor(102, 106, 109), 1);

            SizeF page2Size = page2.GetClientSize();
            float leftMargin = 20f;
            float rightMargin = 20f;
            float innerWidth = page2Size.Width - leftMargin - rightMargin;
            float fieldSpacing = 10f;
            float fieldWidth = innerWidth / 2f - 5f;
            float y2 = 20f;

            // Employment Type
            g2.DrawString("Employment Type", normalFont, blackBrush, new PointF(leftMargin, y2));
            y2 += 25f;
            PdfComboBoxField empType = new PdfComboBoxField(page2, "EmploymentType");
            empType.Bounds = new RectangleF(leftMargin, y2, fieldWidth, 20f);
            empType.Items.Add(new PdfListFieldItem("-- Select --", "Select"));
            empType.Items.Add(new PdfListFieldItem("Full-Time", "FT"));
            empType.Items.Add(new PdfListFieldItem("Part-Time", "PT"));
            empType.Items.Add(new PdfListFieldItem("Contract", "C"));
            empType.Items.Add(new PdfListFieldItem("Temporary", "T"));
            empType.SelectedIndex = 0;
            document.Form.Fields.Add(empType);
            y2 += 40f;

            // Declaration & Signature
            g2.DrawLine(grayPen, new PointF(leftMargin, y2), new PointF(page2Size.Width - rightMargin, y2));
            y2 += 20f;
            RectangleF sectionRect = new RectangleF(leftMargin, y2, innerWidth, 20f);
            g2.DrawRectangle(tealBrush, sectionRect);
            g2.DrawString("Declaration & Signature", boldFont, whiteBrush, new PointF(leftMargin + 5f, y2 + 3f));
            y2 += 35f;

            RectangleF declRect = new RectangleF(leftMargin, y2, innerWidth, 55f);
            PdfSolidBrush lightBlue = new PdfSolidBrush(new PdfColor(220, 240, 255));
            g2.DrawRectangle(lightBlue, declRect);
            g2.DrawString(
                "I declare that all information provided in this application is true, accurate, and complete. I understand that any misrepresentation or omission of information may result in disqualification from consideration or, if employed, dismissal. I consent to the collection and processing of my personal data for recruitment purposes.",
                normalFont,
                blackBrush,
                new RectangleF(leftMargin + 5f, y2 + 5f, innerWidth - 10f, 70f));
            y2 += 75f;

            // Signature and Date
            g2.DrawString("Applicant Signature *", boldFont, blackBrush, new PointF(leftMargin, y2));
            PdfSignatureField signatureField = new PdfSignatureField(page2, "ApplicantSignature");
            signatureField.Bounds = new RectangleF(leftMargin, y2 + 15f, fieldWidth, 40f);
            signatureField.BorderColor = new PdfColor(Color.Black);
            signatureField.BorderWidth = 1f;
            signatureField.BorderStyle = PdfBorderStyle.Solid;
            document.Form.Fields.Add(signatureField);

            g2.DrawString("Date *", boldFont, blackBrush, new PointF(leftMargin + fieldWidth + fieldSpacing, y2));
            PdfTextBoxField dateField = new PdfTextBoxField(page2, "SignatureDate");
            dateField.Bounds = new RectangleF(leftMargin + fieldWidth + fieldSpacing, y2 + 15f, fieldWidth, 40f);
            document.Form.Fields.Add(dateField);
            y2 += 75f;

            // Separator
            g2.DrawLine(grayPen, new PointF(leftMargin, y2), new PointF(page2Size.Width - rightMargin, y2));
            y2 += 20f;

            // Additional Terms & Conditions
            sectionRect = new RectangleF(leftMargin, y2, innerWidth, 20f);
            g2.DrawRectangle(tealBrush, sectionRect);
            g2.DrawString("Additional Terms & Conditions", boldFont, whiteBrush, new PointF(leftMargin + 5f, y2 + 3f));
            y2 += 40f;

            PdfCheckBoxField t1 = new PdfCheckBoxField(page2, "TermsAgree");
            t1.Bounds = new RectangleF(leftMargin, y2, 15f, 15f);
            document.Form.Fields.Add(t1);
            g2.DrawString("I agree to the terms and conditions of employment", normalFont, blackBrush, new PointF(leftMargin + 20f, y2));
            y2 += 35f;

            PdfCheckBoxField t2 = new PdfCheckBoxField(page2, "BackgroundCheck");
            t2.Bounds = new RectangleF(leftMargin, y2, 15f, 15f);
            document.Form.Fields.Add(t2);
            g2.DrawString("I authorize background check and reference verification", normalFont, blackBrush, new PointF(leftMargin + 20f, y2));
            y2 += 35f;

            PdfCheckBoxField t3 = new PdfCheckBoxField(page2, "PrivacyPolicy");
            t3.Bounds = new RectangleF(leftMargin, y2, 15f, 15f);
            document.Form.Fields.Add(t3);
            g2.DrawString("I have read and accepted the Privacy Policy", normalFont, blackBrush, new PointF(leftMargin + 20f, y2));
            y2 += 35f;

            // Submission info and button
            g2.DrawLine(grayPen, new PointF(leftMargin, y2), new PointF(page2Size.Width - rightMargin, y2));
            y2 += 20f;
            g2.DrawString("* Required field", normalFont, blackBrush, new PointF(leftMargin, y2));
            y2 += 35f;

            PdfButtonField submit = new PdfButtonField(page2, "Submit");
            submit.Bounds = new RectangleF(350f, y2 + 6f, 130f, 15f);
            submit.Font = boldFont;
            submit.Text = "Submit Application";
            submit.BackColor = new PdfColor(34, 139, 34);
            submit.ForeColor = new PdfColor(255, 255, 255);
            submit.BorderColor = new PdfColor(34, 139, 34);
            PdfJavaScriptAction javaAction = new PdfJavaScriptAction(
            "address = app.response(\"Enter an e-mail address.\",\"SEND E-MAIL\",\"\");"
            + "if (address)" +


            "{ " +
            "cmdLine = \"mailto:\" + address;" +

            "this.submitForm(cmdLine,true,false,\"Remarks\");" +

            "}");

            submit.Actions.GotFocus = javaAction;
            document.Form.Fields.Add(submit);
            document.Form.SetDefaultAppearance(false);
        }

        /// <summary>
        /// Creates first page in the document.
        /// </summary>
        private void CreateFirstPage()
        {
            // Create first page per the sample (Header, Personal Info, Education, Employment History)
            PdfPage page1 = document.Pages.Add();
            PdfGraphics g = page1.Graphics;
            SizeF page1Size = page1.GetClientSize();

            // Fonts
            PdfFont titleFont = new PdfStandardFont(PdfFontFamily.Helvetica, 17, PdfFontStyle.Regular);
            PdfFont subTitleFont = new PdfStandardFont(PdfFontFamily.Helvetica, 9, PdfFontStyle.Regular);
            PdfFont normalFont = new PdfStandardFont(PdfFontFamily.Helvetica, 10, PdfFontStyle.Regular);
            PdfFont boldFont = new PdfStandardFont(PdfFontFamily.Helvetica, 10, PdfFontStyle.Bold);

            // Brushes and pens
            PdfSolidBrush tealBrush = new PdfSolidBrush(new PdfColor(0, 128, 128));
            PdfSolidBrush blackBrush = new PdfSolidBrush(new PdfColor(0, 0, 0));
            PdfSolidBrush whiteBrush = new PdfSolidBrush(new PdfColor(255, 255, 255));
            PdfSolidBrush navyBrush = new PdfSolidBrush(new PdfColor(19, 43, 66));
            PdfPen navyPen = new PdfPen(new PdfColor(19, 43, 66), 1);
            PdfPen grayPen = new PdfPen(new PdfColor(102, 106, 109), 1);

            float y = 20f;
            float pageWidth = page1Size.Width;
            float leftMargin = 20f;
            float rightMargin = 20f;
            float innerWidth = pageWidth - leftMargin - rightMargin;
            float fieldSpacing = 10f;
            float fieldWidth = innerWidth / 2f - 5f;

            // Header section (rounded rectangle)
            RectangleF headerRect = new RectangleF(leftMargin, y, innerWidth, 55f);
            PdfPath headerPath = RoundedRect(headerRect, 5);
            g.DrawPath(navyPen, navyBrush, headerPath);
            y += 10f;
            g.DrawString("Job Application", titleFont, whiteBrush, new PointF(leftMargin + 10f, y));
            y += 25f;
            g.DrawString(
                "We look forward to receiving your application. please fill in all required fields.",
                subTitleFont,
                tealBrush,
                new RectangleF(leftMargin + 10f, y, innerWidth - 20f, 30f));
            y += 35f;

            // Personal Information section header
            RectangleF sectionRect = new RectangleF(leftMargin, y, innerWidth, 20f);
            g.DrawRectangle(tealBrush, sectionRect);
            g.DrawString("Personal Information", boldFont, whiteBrush, new PointF(leftMargin + 5f, y + 3f));
            y += 35f;

            // First Name
            g.DrawString("First Name *", normalFont, blackBrush, new PointF(leftMargin, y));
            RectangleF firstNameBounds = new RectangleF(leftMargin, y + 15f, fieldWidth, 20f);
            PdfTextBoxField firstNameField = new PdfTextBoxField(page1, "FirstName");
            firstNameField.Bounds = firstNameBounds;
            document.Form.Fields.Add(firstNameField);

            // Last Name
            g.DrawString("Last Name *", normalFont, blackBrush, new PointF(leftMargin + fieldWidth + fieldSpacing, y));
            RectangleF lastNameBounds = new RectangleF(leftMargin + fieldWidth + fieldSpacing, y + 15f, fieldWidth, 20f);
            PdfTextBoxField lastNameField = new PdfTextBoxField(page1, "LastName");
            lastNameField.Bounds = lastNameBounds;
            document.Form.Fields.Add(lastNameField);
            y += 50f;

            // Email Address and Phone
            g.DrawString("Email Address *", normalFont, blackBrush, new PointF(leftMargin, y));
            RectangleF emailBounds = new RectangleF(leftMargin, y + 15f, fieldWidth, 20f);
            PdfTextBoxField emailField = new PdfTextBoxField(page1, "Email");
            emailField.Bounds = emailBounds;
            document.Form.Fields.Add(emailField);

            g.DrawString("Business Phone", normalFont, blackBrush, new PointF(leftMargin + fieldWidth + fieldSpacing, y));
            RectangleF phoneBounds = new RectangleF(leftMargin + fieldWidth + fieldSpacing, y + 15f, fieldWidth, 20f);
            PdfTextBoxField phoneField = new PdfTextBoxField(page1, "Phone");
            phoneField.Bounds = phoneBounds;
            document.Form.Fields.Add(phoneField);
            y += 50f;

            // Position Applied For
            g.DrawString("Position Applied For *", normalFont, blackBrush, new PointF(leftMargin, y));
            RectangleF positionBounds = new RectangleF(leftMargin, y + 15f, fieldWidth, 20f);
            PdfComboBoxField positionField = new PdfComboBoxField(page1, "Position");
            positionField.Bounds = positionBounds;
            positionField.Items.Add(new PdfListFieldItem("-- Select a role --", "SR"));
            positionField.Items.Add(new PdfListFieldItem("Software Engineer", "SE"));
            positionField.Items.Add(new PdfListFieldItem("Senior Developer", "SD"));
            positionField.Items.Add(new PdfListFieldItem("Project Manager", "PM"));
            positionField.Items.Add(new PdfListFieldItem("QA Engineer", "QA"));
            positionField.SelectedIndex = 0;
            document.Form.Fields.Add(positionField);
            y += 55f;

            // Divider
            g.DrawLine(grayPen, new PointF(leftMargin, y), new PointF(pageWidth - rightMargin, y));
            y += 20f;

            // Education section
            sectionRect = new RectangleF(leftMargin, y, innerWidth, 20f);
            g.DrawRectangle(tealBrush, sectionRect);
            g.DrawString("Education", boldFont, whiteBrush, new PointF(leftMargin + 5f, y + 3f));
            y += 35f;

            g.DrawString(
                "Please select the highest level of education you have completed.",
                normalFont,
                blackBrush,
                new PointF(leftMargin, y));
            y += 30f;

            // Education checkboxes - first row
            float checkY = y;
            float x1 = leftMargin;

            PdfCheckBoxField chk = new PdfCheckBoxField(page1, "AssociateDegree");
            chk.Bounds = new RectangleF(x1, checkY, 15f, 15f);
            document.Form.Fields.Add(chk);
            g.DrawString("Associate Degree", normalFont, blackBrush, new PointF(x1 + 20f, checkY));

            x1 = leftMargin + 190f;
            chk = new PdfCheckBoxField(page1, "BachelorDegree");
            chk.Bounds = new RectangleF(x1, checkY, 15f, 15f);
            document.Form.Fields.Add(chk);
            g.DrawString("Bachelor's Degree", normalFont, blackBrush, new PointF(x1 + 20f, checkY));

            x1 = leftMargin + 370f;
            chk = new PdfCheckBoxField(page1, "CollegeDiploma");
            chk.Bounds = new RectangleF(x1, checkY, 15f, 15f);
            document.Form.Fields.Add(chk);
            g.DrawString("College / Diploma", normalFont, blackBrush, new PointF(x1 + 20f, checkY));
            y += 35f;

            // Education checkboxes - second row
            x1 = leftMargin;
            chk = new PdfCheckBoxField(page1, "Postgraduate");
            chk.Bounds = new RectangleF(x1, y, 15f, 15f);
            document.Form.Fields.Add(chk);
            g.DrawString("Postgraduate (PG)", normalFont, blackBrush, new PointF(x1 + 20f, y));

            x1 = leftMargin + 190f;
            chk = new PdfCheckBoxField(page1, "MBA");
            chk.Bounds = new RectangleF(x1, y, 15f, 15f);
            document.Form.Fields.Add(chk);
            g.DrawString("MBA", normalFont, blackBrush, new PointF(x1 + 20f, y));
            y += 35f;

            // Divider
            g.DrawLine(grayPen, new PointF(leftMargin, y), new PointF(pageWidth - rightMargin, y));
            y += 20f;

            // Employment History section
            sectionRect = new RectangleF(leftMargin, y, innerWidth, 20f);
            g.DrawRectangle(tealBrush, sectionRect);
            g.DrawString("Employment History", boldFont, whiteBrush, new PointF(leftMargin + 5f, y + 3f));
            y += 35f;

            g.DrawString("List your most recent position first.", normalFont, blackBrush, new PointF(leftMargin, y));
            y += 25f;

            // Currently Employed checkbox
            chk = new PdfCheckBoxField(page1, "CurrentlyEmployed");
            chk.Bounds = new RectangleF(leftMargin, y, 15f, 15f);
            document.Form.Fields.Add(chk);
            g.DrawString("I am currently employed at this company", normalFont, blackBrush, new PointF(leftMargin + 20f, y));
            y += 35f;

            // Job Title and Employer
            g.DrawString("Job Title *", normalFont, blackBrush, new PointF(leftMargin, y));
            PdfTextBoxField jobTitleField = new PdfTextBoxField(page1, "JobTitle");
            jobTitleField.Bounds = new RectangleF(leftMargin, y + 15f, fieldWidth, 20f);
            document.Form.Fields.Add(jobTitleField);

            g.DrawString("Employer *", normalFont, blackBrush, new PointF(leftMargin + fieldWidth + fieldSpacing, y));
            PdfTextBoxField employerField = new PdfTextBoxField(page1, "Employer");
            employerField.Bounds = new RectangleF(leftMargin + fieldWidth + fieldSpacing, y + 15f, fieldWidth, 20f);
            document.Form.Fields.Add(employerField);
            y += 50f;

            // Salary and Reason for Leaving
            g.DrawString("Annual Salary", normalFont, blackBrush, new PointF(leftMargin, y));
            PdfTextBoxField salaryField = new PdfTextBoxField(page1, "Salary");
            salaryField.Bounds = new RectangleF(leftMargin, y + 15f, fieldWidth, 20f);
            document.Form.Fields.Add(salaryField);

            g.DrawString("Reason for Leaving", normalFont, blackBrush, new PointF(leftMargin + fieldWidth + fieldSpacing, y));
            PdfTextBoxField reasonField = new PdfTextBoxField(page1, "ReasonForLeaving");
            reasonField.Bounds = new RectangleF(leftMargin + fieldWidth + fieldSpacing, y + 15f, fieldWidth, 20f);
            document.Form.Fields.Add(reasonField);
            y += 50f;

            // Duties (multiline)
            g.DrawString("Key Duties & Responsibilities *", normalFont, blackBrush, new PointF(leftMargin, y));
            PdfTextBoxField dutiesField = new PdfTextBoxField(page1, "Duties");
            dutiesField.Bounds = new RectangleF(leftMargin, y + 15f, innerWidth, 60f);
            dutiesField.Multiline = true;
            document.Form.Fields.Add(dutiesField);
        }

        /// <summary>
        /// Creates textbox and adds it in the form.
        /// </summary>
        /// <param name="page"></param>
        /// <param name="text"></param>
        /// <param name="tooltip"></param>
        /// <param name="f"></param>
        /// <param name="bounds"></param>
        protected void CreateTextBox(PdfPage page, string text, string tooltip, Font f, RectangleF bounds)
        {
            // Create a Text box field.
            PdfTextBoxField textBoxField = new PdfTextBoxField(page, text);

            PdfTrueTypeFont font = new PdfTrueTypeFont(f);

            //Set properties to the textbox.
            textBoxField.Font = font;
            textBoxField.BorderColor = new PdfColor(Color.Gray);
            textBoxField.BorderStyle = PdfBorderStyle.Beveled;
            textBoxField.Bounds = bounds;
            textBoxField.ToolTip = tooltip;

            document.Form.Fields.Add(textBoxField);
        }

        /// <summary>
        /// Draws a rounded rectangle path matching the requested bounds and radius.
        /// </summary>
        private PdfPath RoundedRect(RectangleF bounds, int radius)
        {
            int diameter = radius * 2;
            SizeF size = new SizeF(diameter, diameter);
            RectangleF arc = new RectangleF(bounds.Location, size);
            PdfPath path = new PdfPath();
            if (radius == 0)
            {
                path.AddRectangle(bounds);
                return path;
            }
            // top-left arc
            path.AddArc(arc, 180, 90);
            // top-right arc
            arc.X = bounds.Right - diameter;
            path.AddArc(arc, 270, 90);
            // bottom-right arc
            arc.Y = bounds.Bottom - diameter;
            path.AddArc(arc, 0, 90);
            // bottom-left arc
            arc.X = bounds.Left;
            path.AddArc(arc, 90, 90);
            // close figure
            path.CloseFigure();
            return path;
        }

        /// <summary>
        /// Gets the full path of the PDF template or image.
        /// </summary>
        /// <param name="fileName">Name of the file</param>
        /// <param name="image">True if image</param>
        /// <returns>Path of the file</returns>
        private string GetFullTemplatePath(string fileName, bool image)
        {
#if NETCORE
            string fullPath = @"..\..\..\..\..\..\..\Common\";
#else
            string fullPath = @"..\..\..\..\..\..\Common\";
#endif
            string folder = image ? "Images" : "Data";

            return string.Format(@"{0}{1}\PDF\{2}", fullPath, folder, fileName);
        }
        #endregion
    }
	/// <summary>
    /// Represents a class that is used to find the licensing file for Syncfusion controls.
    /// </summary>
    public class DemoCommon
    {

        /// <summary>
        /// Finds the license key from the Common folder.
        /// </summary>
        /// <returns>Returns the license key.</returns>
        public static string FindLicenseKey()
        {

            string licenseKeyFile = "Common\\SyncfusionLicense.txt";

            for (int n = 0; n < 20; n++)
            {
                if (!System.IO.File.Exists(licenseKeyFile))
                {
                    licenseKeyFile = @"..\" + licenseKeyFile;
                    continue;
                }
                return System.IO.File.ReadAllText(licenseKeyFile);
            }
            return string.Empty;
        }
    }
}
