<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>PDFToImage</AssemblyName>
    <RootNamespace>PDFToImage</RootNamespace>
    <DefineConstants>NETCORE</DefineConstants>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Syncfusion.PdfToImageConverter.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net8.0\Syncfusion.PdfToImageConverter.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Tools.Windows">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net8.0\Syncfusion.Tools.Windows.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Shared.Base">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net8.0\Syncfusion.Shared.Base.dll</HintPath>
    </Reference>
    <Reference Include="Syncfusion.Licensing">
      <HintPath>$(SyncfusionInstallLocation)\precompiledassemblies\net8.0\Syncfusion.Licensing.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>